chunking: 
  method: section # fixed | overlap | paragraph | section

fixed:
  chunk_size: 10

overlap:
  chunk_size: 10
  overlap_size: 2

paragraph:
  min_length: 5
  max_length: 500

section:
  min_length: 5
  max_length: 500